service: wombo-api-service
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-webpack-prisma
  - serverless-deployment-bucket
  - serverless-prune-plugin
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage}
  versionFunctions: false
  deploymentBucket:
    name: ${self:service}-${opt:stage}-deployment-bucket
    maxPreviousDeploymentArtifacts: 1
  apiGateway:
    minimumCompressionSize: 512 # Compress response when larger than specified size in bytes
    shouldStartNameWithService: true
    apiKeys:
      - name: ${env:SUBDOMAIN}-apiKey
        value: ${env:DEFAULT_API_KEY}
  environment:
    SUBDOMAIN: ${env:SUBDOMAIN}
    DEFAULT_API_KEY: ${env:DEFAULT_API_KEY}
    JWT_SECRET: ${env:JWT_SECRET}
    SENTRY_DSN: ${env:SENTRY_DSN}
    SENTRY_ENVIRONMENT: ${env:SENTRY_ENVIRONMENT}
    SENTRY_ERROR_RATE: ${env:SENTRY_ERROR_RATE}
    SENTRY_TRANSACTION_RATE: ${env:SENTRY_TRANSACTION_RATE}
    COCKROACHDB_DATABASE_URL: ${env:COCKROACHDB_DATABASE_URL}
    PRISMA_DATAPROXY: ${env:PRISMA_DATAPROXY}
    CHECKPOINT_DISABLE: ${env:CHECKPOINT_DISABLE}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
    DISCORD_BOT_TOKEN: ${env:DISCORD_BOT_TOKEN}
    DISCORD_GUILD_WOMBO: ${env:DISCORD_GUILD_WOMBO}
    BOOKING_DATABASE_URL: ${env:BOOKING_DATABASE_URL}
    FACEIT_API_KEY: ${env:FACEIT_API_KEY}
    FACEIT_USER_TOKEN: ${env:FACEIT_USER_TOKEN}
    TWITTER_BOT_VAL_APP_TOKEN: ${env:TWITTER_BOT_VAL_APP_TOKEN}
    TWITTER_BOT_VAL_APP_SECRET: ${env:TWITTER_BOT_VAL_APP_SECRET}
    TWITTER_BOT_VAL_ACCESS_TOKEN: ${env:TWITTER_BOT_VAL_ACCESS_TOKEN}
    TWITTER_BOT_VAL_ACCESS_SECRET: ${env:TWITTER_BOT_VAL_ACCESS_SECRET}
    TWITTER_BOT_LOL_APP_TOKEN: ${env:TWITTER_BOT_LOL_APP_TOKEN}
    TWITTER_BOT_LOL_APP_SECRET: ${env:TWITTER_BOT_LOL_APP_SECRET}
    TWITTER_BOT_LOL_ACCESS_TOKEN: ${env:TWITTER_BOT_LOL_ACCESS_TOKEN}
    TWITTER_BOT_LOL_ACCESS_SECRET: ${env:TWITTER_BOT_LOL_ACCESS_SECRET}
    NEATQUEUE_API_KEY:  ${env:NEATQUEUE_API_KEY}

custom:
  serverless-offline:
    apiKey: ${env:DEFAULT_API_KEY}
    httpPort: ${env:SERVERLESS_OFFLINE_HTTP_PORT, 8001}
    lambdaPort: ${env:SERVERLESS_OFFLINE_LAMBDA_PORT, 3001}
  webpack:
    includeModules: true
  domainEnabled:
    local: false
    test: true
    staging: true
    production: true
  customDomain:
    enabled: ${self:custom.domainEnabled.${self:provider.stage}}
    domainName: ${env:SUBDOMAIN}.wombo.gg
    certificateName: 'wombo.gg'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  faceItBotEnabled:
    local: false
    test: false
    staging: false
    production: true
  neatQueueBotEnabled:
    local: false
    test: false
    staging: false
    production: true
  prune:
    automatic: true
    includeLayers: true
    number: 0

functions:
  # Coaches
  listCoaches:
    handler: src/index.listCoachesHandler
    events:
      - http:
          path: /coaches
          method: get
          private: true
  getCoach:
    handler: src/index.getCoachHandler
    events:
      - http:
          path: /coaches/{username}
          method: get
          private: true
  # Students
  signinStudent:
    handler: src/index.signinStudentHandler
    events:
      - http:
          path: /students/signin
          method: post
          private: true
  signupStudent:
    handler: src/index.signupStudentHandler
    events:
      - http:
          path: /students/signup
          method: post
          private: true
  getStudentMe:
    handler: src/index.getStudentMeHandler
    events:
      - http:
          path: /students/me
          method: get
          private: true
  getStudentMeOrders:
    handler: src/index.getStudentMeOrdersHandler
    events:
      - http:
          path: /students/me/orders
          method: get
          private: true
  updateStudentMe:
    handler: src/index.updateStudentMeHandler
    events:
      - http:
          path: /students/me
          method: put
          private: true
  setStudentFreePass:
    handler: src/index.setStudentMeFreePassHandler
    events:
      - http:
          path: /students/me/freepass
          method: post
          private: true
  listStudentsFreePassEnrolled:
    handler: src/index.listStudentsFreePassEnrolledHandler
    events:
      - http:
          path: /students/freepass
          method: get
          private: true
  # Tiers
  getTier:
    handler: src/index.getTierHandler
    events:
      - http:
          path: /tiers/{id}
          method: get
          private: true
  listTiers:
    handler: src/index.listTiersHandler
    events:
      - http:
          path: /tiers
          method: get
          private: true
  # VideoGames
  listVideoGames:
    handler: src/index.listVideoGamesHandler
    events:
      - http:
          path: /videogames
          method: get
          private: true
  # Coupons
  getCoupon:
    handler: src/index.getCouponHandler
    events:
      - http:
          path: /coupons/{name}
          method: get
          private: true
  createCoupon:
    handler: src/index.createCouponHandler
    events:
      - http:
          path: /coupons
          method: post
          private: true
  # Stripe
  stripeWebhook:
    handler: src/index.stripeWebhookHandler
    events:
      - http:
          path: /stripe/webhook
          method: post
          private: false
  # Booking
  bookingWebhook:
    handler: src/index.bookingWebhookHandler
    events:
      - http:
          path: /booking/webhook
          method: post
          private: true
  listBookingSessions:
    handler: src/index.listBookingSessionsHandler
    events:
      - http:
          path: /booking/sessions
          method: get
          private: true
  # Discord
  discordConnect:
    handler: src/index.discordConnectHandler
    events:
      - http:
          path: /discord/connect
          method: post
          private: true
  # League Hub Valorant
  leagueHubEnrollment:
    handler: src/index.leagueHubEnrollmentHandler
    events:
      - http:
          path: /league/hub/enrollment
          method: post
          private: true
  leagueHubEnrolled:
    handler: src/index.leagueHubEnrolledHandler
    events:
      - http:
          path: /league/hub/enrollment
          method: get
          private: true
  # League Hub League of Legends
  leagueHubLoLEnrollment:
    handler: src/index.leagueHubLoLEnrollmentHandler
    events:
      - http:
          path: /league/hub/lol/enrollment
          method: post
          private: true
  leagueHubLoLEnrolled:
    handler: src/index.leagueHubLoLEnrolledHandler
    events:
      - http:
          path: /league/hub/lol/enrollment
          method: get
          private: true
  # League High School
  leagueHighSchoolEnrollment:
    handler: src/index.leagueHighSchoolEnrollmentHandler
    events:
      - http:
          path: /league/highschool/enrollment
          method: post
          private: true
  leagueHighSchoolEnrolled:
    handler: src/index.leagueHighSchoolEnrolledHandler
    events:
      - http:
          path: /league/highschool/enrollment
          method: get
          private: true
  # Provider: Face It
  faceItHubsLeaderboard:
    handler: src/index.faceItHubsLeaderboardHandler
    events:
      - http:
          path: /providers/faceit/hubsleaderboard
          method: get
          private: true
  faceItHubsQueue:
    handler: src/index.faceItHubsQueueHandler
    events:
      - http:
          path: /providers/faceit/hubsqueue
          method: get
          private: true
  faceItBotHubsQueue:
    handler: src/index.faceItBotHubsQueueHandler
    events:
      - schedule:
          rate: rate(15 minutes)
          enabled: ${self:custom.faceItBotEnabled.${self:provider.stage}}
  # Provider: Neat Queue
  neatQueueChannelsLeaderboard:
    handler: src/index.neatQueueChannelsLeaderboardHandler
    events:
      - http:
          path: /providers/neatqueue/channelsleaderboard
          method: get
          private: true
  neatQueueChannelsQueue:
    handler: src/index.neatQueueChannelsQueueHandler
    events:
      - http:
          path: /providers/neatqueue/channelsqueue
          method: get
          private: true
  neatQueueBotChannelsQueue:
    handler: src/index.neatQueueBotChannelsQueueHandler
    events:
      - schedule:
          rate: rate(15 minutes)
          enabled: ${self:custom.neatQueueBotEnabled.${self:provider.stage}}
