export const DEFAULT_COMPETITION_FIELDS = [
  'id',
  'codename',
  'videoGameId',
  'cmsVideoGameHandleId',
  'status',
  'metadata',
  'registrationStatus',
  'participants',
  'challenges',
  'predictions',
  'isActive',
  'createdAt',
  'updatedAt',
]
