export const DEFAULT_COMPETITION_FIELDS = [
  'id',
  'codename',
  'type',
  'start',
  'end',
  'videoGame',
  'status',
  'registrationStatus',
  'participants',
  'challenges',
  'isActive',
  'createdAt',
  'updatedAt',
]
