-- AlterTable
ALTER TABLE "Stat" ALTER COLUMN "rating" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "highestRating" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "highestRatingDate" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "highestRatingDate" DROP DEFAULT;
ALTER TABLE "Stat" ALTER COLUMN "ratingDelta" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "accOpponentsRating" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "highestRatingOpponent" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "matchesWon" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "matchesDraw" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "matchesLost" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "matchesGoalsFor" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "matchesGoalsAgainst" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "tournamentsFirstPlace" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "tournamentsSecondPlace" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "tournamentsThirdPlace" DROP NOT NULL;
ALTER TABLE "Stat" ALTER COLUMN "metadata" DROP NOT NULL;
