import { generateUserToken } from '~/services/generateUserToken'
import { upsertStudent } from '~/services/students'
import { buildHandler, isNilOrEmpty } from '~/utils'

const handler = async ({ body }, res) => {
  const { provider, data } = body

  if (isNilOrEmpty(data.email)) {
    data.email = `${data[provider].id}@autogenerated.wombo.gg`
  }

  data.lastLogin = new Date()

  const { id, email } = await upsertStudent(data)

  const accessToken = await generateUserToken({ id, email })

  return res.json({ accessToken })
}

export const signupStudentHandler = buildHandler('/students/signup', 'post', handler)
