name: Deploy to test env
on:
  workflow_dispatch: null
jobs:
  deploy-to-test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - id: install-npm-dependencies
        name: Install Dependencies
        run: npm ci
      - id: configure-aws-credentials
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - id: do-test-deploy
        name: Deploy
        run: npm run deploy:test
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN_TEST }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY_TEST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT_TEST }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE_TEST }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE_TEST }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL_TEST }}
          PRISMA_DATAPROXY: ${{ secrets.PRISMA_DATAPROXY_TEST }}
          CHECKPOINT_DISABLE: ${{ secrets.CHECKPOINT_DISABLE }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY_TEST }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET_TEST }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_WOMBO: ${{ secrets.DISCORD_GUILD_WOMBO }}
          BOOKING_DATABASE_URL: ${{ secrets.BOOKING_DATABASE_URL_TEST }}
