name: Deploy to staging env
on:
  push:
    branches:
      - staging
  workflow_dispatch: null
jobs:
  do-lint:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-dependencies
        name: Install Dependencies
        run: npm ci
      - id: do-lint
        name: Lint
        run: npm run lint
  do-staging-deploy:
    runs-on: ubuntu-latest
    needs: do-lint
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-npm-dependencies
        name: Install Dependencies
        run: npm ci
      - id: configure-aws-credentials
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - id: do-production-build
        name: Build
        run: npm run build:production
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN_STAGING }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY_STAGING }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT_STAGING }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE_STAGING }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE_STAGING }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL_STAGING }}
          PRISMA_DATAPROXY: ${{ secrets.PRISMA_DATAPROXY_STAGING }}
          CHECKPOINT_DISABLE: ${{ secrets.CHECKPOINT_DISABLE }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY_STAGING }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET_STAGING }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_WOMBO: ${{ secrets.DISCORD_GUILD_WOMBO }}
          BOOKING_DATABASE_URL: ${{ secrets.BOOKING_DATABASE_URL_STAGING }}
      - id: do-staging-deploy
        name: Deploy
        run: npm run deploy:staging
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN_STAGING }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY_STAGING }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT_STAGING }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE_STAGING }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE_STAGING }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL_STAGING }}
          PRISMA_DATAPROXY: ${{ secrets.PRISMA_DATAPROXY_STAGING }}
          CHECKPOINT_DISABLE: ${{ secrets.CHECKPOINT_DISABLE }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY_STAGING }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET_STAGING }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_WOMBO: ${{ secrets.DISCORD_GUILD_WOMBO }}
          BOOKING_DATABASE_URL: ${{ secrets.BOOKING_DATABASE_URL_STAGING }}
