name: Deploy to test env
on:
  workflow_dispatch: null
jobs:
  deploy-to-test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-dependencies
        name: Install Dependencies
        run: npm ci
      - id: configure-aws-credentials
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - id: do-test-deploy
        name: Deploy
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN_TEST }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY_TEST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT_TEST }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE_TEST }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE_TEST }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL_TEST }}
          CHECKPOINT_DISABLE: 1
        run: npm run deploy:test
