name: Deploy to production env
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  do-github-release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-dependencies
        name: Install Dependencies
        run: npm ci
      - id: do-github-release
        name: Github release
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: wombolabs
          SENTRY_PROJECT: wombo-api-service
        run: npm run release
  do-production-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: do-github-release
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-dependencies
        name: Install Dependencies
        run: npm ci
      - id: configure-aws-credentials
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - id: do-production-build
        name: Build
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL }}
          CHECKPOINT_DISABLE: 1
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_WOMBO: ${{ secrets.DISCORD_GUILD_WOMBO }}
          DISCORD_GUILD_CATEGORY_CHALLENGES: ${{ secrets.DISCORD_GUILD_CATEGORY_CHALLENGES }}
          BOOKING_DATABASE_URL: ${{ secrets.BOOKING_DATABASE_URL }}
        run: npm run build:production
      - id: do-production-deploy
        name: Deploy
        env:
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL }}
          CHECKPOINT_DISABLE: 1
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_WOMBO: ${{ secrets.DISCORD_GUILD_WOMBO }}
          DISCORD_GUILD_CATEGORY_CHALLENGES: ${{ secrets.DISCORD_GUILD_CATEGORY_CHALLENGES }}
          BOOKING_DATABASE_URL: ${{ secrets.BOOKING_DATABASE_URL }}
        run: npm run deploy:production
