name: Deploy to production env
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  setup-npm-cache:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-npm-dependencies
        name: Install Dependencies
        run: npm ci
        if: steps.cache-deps.outputs.cache-hit != 'true'
  do-production-deploy:
    runs-on: ubuntu-latest
    needs: setup-npm-cache
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-npm-dependencies
        name: Install Dependencies
        run: npm ci
        if: steps.manage-test-build-cache.cache-hit != 'true'
      - id: configure-aws-credentials
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - id: do-production-build
        name: Build
        run: npm run build:production
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_WOMBO: ${{ secrets.DISCORD_GUILD_WOMBO }}
      - id: do-github-release
        name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: wombolabs
          SENTRY_PROJECT: wombo-api-service
      - id: do-production-deploy
        name: Deploy
        run: npm run deploy:production
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
          SENTRY_ERROR_RATE: ${{ secrets.SENTRY_ERROR_RATE }}
          SENTRY_TRANSACTION_RATE: ${{ secrets.SENTRY_TRANSACTION_RATE }}
          DEFAULT_API_KEY: ${{ secrets.API_SERVICE_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
          COCKROACHDB_DATABASE_URL: ${{ secrets.COCKROACHDB_DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_WOMBO: ${{ secrets.DISCORD_GUILD_WOMBO }}
