name: Lint and Tests
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  setup-npm-cache:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.7
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-npm-dependencies
        name: Install Dependencies
        run: npm ci
        if: steps.cache-deps.outputs.cache-hit != 'true'
  do-lint:
    runs-on: ubuntu-latest
    needs: setup-npm-cache
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.7
      - id: manage-npm-cache
        name: Cache/Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - id: install-npm-dependencies
        name: Install Dependencies
        env:
          HUSKY_SKIP_INSTALL: 1
        run: npm ci
      - id: do-lint
        name: Lint
        run: npm run lint
